# Generated by Django 3.2 on 2022-01-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='techars',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.teacher'),
            preserve_default=False,
        ),
    ]
