# Generated by Django 3.2 on 2022-01-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220107_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='student', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='techars',
            field=models.ManyToManyField(related_name='teacher', to='students.Teacher'),
        ),
    ]
